image: atlassian/default-image:3

pipelines:
    branches:
        develop:
            - step:
                  name: 'Deploy to Production'
                  deployment: Production
                  script:
                      - pipe: atlassian/ssh-run:0.8.1
                        variables:
                            SSH_USER: $SSH_USER
                            SERVER: $SERVER
                            SSH_KEY: $SSH_KEY
                            MODE: 'command'
                            COMMAND: |
                                cd $FRONTEND_APP_PATH
                                git pull origin develop
                                docker-compose up --build -d
